### ISSUE TITLE
> 请问各位大佬，文章里 “将频繁重绘或者回流的节点设置为图层，图层能够阻止该节点的渲染行为影响别的节点。比如对于 video 标签来说，浏览器会自动将该节点变为图层。” 这句话中的图层是什么意思呢？我在百度上搜了好久，没找到答案，请各位大佬赐教了，谢谢

### ISSUE THREAD

**Issue by ZhuZicai** [ljianshu/Blog#90]
> 请问各位大佬，文章里 “将频繁重绘或者回流的节点设置为图层，图层能够阻止该节点的渲染行为影响别的节点。比如对于 video 标签来说，浏览器会自动将该节点变为图层。” 这句话中的图层是什么意思呢？我在百度上搜了好久，没找到答案，请各位大佬赐教了，谢谢
浏览器->F12->设置->Layers ->你可以进行360°操作。（找有轮播的页面查看，你会看到一层一层。这就是浏览器在渲染的时候产生的图层。）图层的实现可以有多种方式大多是靠css设置。

_Originally posted by @752337625 in https://github.com/ljianshu/Blog/issues/51#issuecomment-792187624_

**Comment by ZhuZicai** [comment]
再打扰一下，我在F12的设置中，没有看到Layers呢。你看我找的地方对吗？谢谢
![2021-03-12_142454](https://user-images.githubusercontent.com/60442239/110901279-0bdad080-833f-11eb-8b67-a1fdff0e15b0.png)
![2021-03-12_142129](https://user-images.githubusercontent.com/60442239/110901288-1006ee00-833f-11eb-9a52-c7beb60fd8c6.png)

**Comment by 752337625** [comment]
![image](https://user-images.githubusercontent.com/46662524/111030955-192bb400-8440-11eb-9a04-4e4efe9e4ab6.png)

**Comment by 752337625** [comment]
![image](https://user-images.githubusercontent.com/46662524/111030992-44ae9e80-8440-11eb-80e2-4d9bdc1536f2.png)

**Comment by ZhuZicai** [comment]
对不起，再次叨扰了。请问如何将html里边的阶段变为图层。我在网上也没扫到，请问应该搜哪些关键字呢？你有没有推荐的文章？还望贵人再次指教了，谢谢

**Comment by 752337625** [comment]
查：CSS3开启GPU硬件加速。

















在 2021-03-15 15:21:58，"ZhuZicai" ***@***.***> 写道：

对不起，再次叨扰了。请问如何将html里边的阶段变为图层。我在网上也没扫到，请问应该搜哪些关键字呢？你有没有推荐的文章？还望贵人再次指教了，谢谢
